image: node:latest

cache:
    paths:
        - node_modules/

build:
    script:
        - npm install copyfiles --save-dev
        - npm install discord.js --save-dev
        - npm install gamedig --save-dev
        - npm install typescript --save-dev
        - npm init --yes
        - npm run execute
    tags:
        - docker
